// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMpbGfCxCEkM1va4Oc2KmwtIgseWlDoEE',
    appId: '1:92971777306:web:fa152e8605737ae5af40a3',
    messagingSenderId: '92971777306',
    projectId: 'mygymbook-94790',
    authDomain: 'mygymbook-94790.firebaseapp.com',
    databaseURL: 'https://mygymbook-94790-default-rtdb.firebaseio.com',
    storageBucket: 'mygymbook-94790.appspot.com',
    measurementId: 'G-L3RPYFD0MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhto-05sWMNRNby9kyunIVl1SgsZVnPXU',
    appId: '1:92971777306:android:39839b9d6b94bea5af40a3',
    messagingSenderId: '92971777306',
    projectId: 'mygymbook-94790',
    databaseURL: 'https://mygymbook-94790-default-rtdb.firebaseio.com',
    storageBucket: 'mygymbook-94790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7EYno_ZkC1Iw3_eqRkJvhYErxkPgV6gs',
    appId: '1:92971777306:ios:f4c4ee9f2638a2cbaf40a3',
    messagingSenderId: '92971777306',
    projectId: 'mygymbook-94790',
    databaseURL: 'https://mygymbook-94790-default-rtdb.firebaseio.com',
    storageBucket: 'mygymbook-94790.appspot.com',
    iosClientId: '92971777306-j4oc7m30pfk8p8m4r2klm1bucdi0e0uh.apps.googleusercontent.com',
    iosBundleId: 'br.com.baz.myGymBook',
  );
}
