name: Flutter ANDROID Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'  # Substitua pela versão desejada, como '2.10.1'

      - name: Upgrade Flutter to the latest version
        run: flutter upgrade

      - name: Setup Flutter
        run: flutter config --no-analytics

      - name: Get dependencies
        run: flutter pub get

      - name: Statically analyze the Dart code for any errors.
        run: flutter analyze .

      - name: Run widget tests for our flutter project.
        run: flutter test

      - name: Start Android App Release Build
        run: flutter build apk

      - name: Upload Android App Build apk
        uses: actions/upload-artifact@v2
        with:
          name: apk-release
          path: build/app/outputs/bundle/release/app-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APPID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk
